db-uri = "postgres://postgres:postgres@localhost:5432/stixnvibes_test"
db-schemas = "public"
db-anon-role = "postgres"
server-port = 54322
jwt-secret = "super-secret-jwt-key-stixnvibes-32-chars-long!"
