export type ProductRow = {
  id: string;
  name: string;
  slug: string;
  price_cents: number;
  compare_at_cents?: number | null;
  stock: number;
  is_featured: boolean;
  customizable: boolean;
  collection: string | null;
  type: string;
  image_url?: string | null;
  images?: string[];
  tags?: string[];
  description?: string | null;
  short_description?: string | null;
  status?: string;
  sku?: string | null;
  barcode?: string | null;
  cost_cents?: number;
  seo_title?: string | null;
  seo_description?: string | null;
  category_id?: string | null;
  is_bundle?: boolean;
  is_limited?: boolean;
  visibility?: string;
  updated_at?: string;
  created_at?: string;
};
